theme = "millzoGo"
baseURL = ""
languageCode = "en-us"
title = "Millzo, Inc."
[taxonomies]
tag = "tags"

[params]
  # Social media links
  linkedin = "https://www.linkedin.com/company/millzo-inc"
  twitter = "https://www.twitter.com/MillzoInc"
  facebook = "https://www.facebook.com/millzoinc"
